name: heroku-jupyter
dependencies:
  # bind notebook version (compatibility to pgcontents)
  - notebook = 5
  - ipywidgets = 7.5.1
  - requests
  # bind ipython version (compatibility to pgcontents)
  - ipython 
  # bind tornado version (websocket problems)
  - tornado = 6.0.4
  # get dependencies for pgcontents
  - certifi = 2020.6.20
  - click = 7.1.2
  - cryptography
  - mako = 1.1.3
  - psycopg2
  - six = 1.15.0
  - sqlalchemy
  - nose = 1.3.7
  - pip:
    - git+git://github.com/Ajuajmal/pgcontents.git
    - git+git://github.com/ipython-contrib/jupyter_contrib_nbextensions.git
